on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Bogdanp/setup-racket@v1.12
      - name: Installing raco-deploy and its dependencies
        run: raco pkg install --no-docs --auto --name raco-deploy
      - name: Compiling raco-deploy and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps raco-deploy
      - name: Testing raco-deploy
        run: raco test --drdr -p raco-deploy
